# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ThomasFish
tagline:          'Hello, nice to meet you.'
description:      'Thomas&39 personal blog.'
url:              http://thomas.fish
baseurl:          /

author:
  name:           'Thomas Fish'
  url:            http://thomas.fish

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
